org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.javaCompile.suppressSourceTargetDeprecationWarning=true

# Workaround for Windows AV file-locking during Gradle transforms cache renames
org.gradle.caching=false
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.unsafe.watch-fs=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
