class ErrorCatalog {
  final int? errorId;       // null before DB insert (AUTOINCREMENT)
  final String code;
  final String description;
  final String category;
  final String severity;     // 'low', 'medium', 'high', 'critical'
  final String recommendation;
  final String normReference; // DIN/EN norm reference
  
  // Consolidation fields
  final String status;        // 'Approved', 'Pending', 'Rejected'
  final String? requestedBy;
  final DateTime? requestDate;
  final int? sourceInspectionDoorId;

  ErrorCatalog({
    this.errorId,
    required this.code,
    required this.description,
    required this.category,
    this.severity = 'medium',
    this.recommendation = '',
    this.normReference = '',
    this.status = 'Approved', // Default for master data
    this.requestedBy,
    this.requestDate,
    this.sourceInspectionDoorId,
  });

  // CopyWith method
  ErrorCatalog copyWith({
    int? errorId,
    String? code,
    String? description,
    String? category,
    String? severity,
    String? recommendation,
    String? normReference,
    String? status,
    String? requestedBy,     
    DateTime? requestDate,
    int? sourceInspectionDoorId,
  }) {
    return ErrorCatalog(
      errorId: errorId ?? this.errorId,
      code: code ?? this.code,
      description: description ?? this.description,
      category: category ?? this.category,
      severity: severity ?? this.severity,
      recommendation: recommendation ?? this.recommendation,
      normReference: normReference ?? this.normReference,
      status: status ?? this.status,
      requestedBy: requestedBy ?? this.requestedBy,
      requestDate: requestDate ?? this.requestDate, 
      sourceInspectionDoorId: sourceInspectionDoorId ?? this.sourceInspectionDoorId,
    );
  }

  Map<String, dynamic> toMap() => {
        if (errorId != null) 'errorId': errorId,
        'code': code,
        'description': description,
        'category': category,
        'severity': severity,
        'recommendation': recommendation,
        'normReference': normReference,
        'status': status, 
        'requestedBy': requestedBy,
        'requestDate': requestDate,
        'sourceInspectionDoorId': sourceInspectionDoorId,
      };

  factory ErrorCatalog.fromMap(Map<String, dynamic> map) => ErrorCatalog(
        errorId: map['errorId'],
        code: map['code'] ?? '',
        description: map['description'] ?? '',
        category: map['category'] ?? '',
        severity: map['severity'] ?? 'medium',
        recommendation: map['recommendation'] ?? '',
        normReference: map['normReference'] ?? '',
        status: map['status'] ?? 'Approved',
        requestedBy: map['requestedBy'],
        requestDate: map['requestDate'] != null 
            ? DateTime.tryParse(map['requestDate']) 
            : null,
        sourceInspectionDoorId: map['sourceInspectionDoorId'],
      );

  @override
  String toString() {
    return '$code - $category: $description';
  }

  /// Compare the content of this catalog entry with another entry.
  /// Returns true only if all import-relevant fields are identical.
  bool isSameContent(ErrorCatalog other) {
    return code == other.code &&
        description == other.description &&
        category == other.category &&
        severity == other.severity &&
        recommendation == other.recommendation &&
        normReference == other.normReference;
  }
}

class ImportConflict {
  final String code;
  final String description;
  final ErrorCatalog incoming;
  final ErrorCatalog? existing;
  final String reason;

  ImportConflict({
    required this.code,
    required this.description,
    required this.incoming,
    this.existing,
    required this.reason,
  });

  @override
  String toString() {
    return 'Konflikt für Code $code: $reason';
  }
}

class ImportResult {
  final int insertedCount;
  final int duplicateCount;
  final List<ImportConflict> conflicts;

  ImportResult({
    required this.insertedCount,
    required this.duplicateCount,
    required this.conflicts,
  });
}

enum ResolutionAction {
  keepExisting,
  replaceExisting,
  addAsNew,
  skip,
}

class ConflictResolution {
  final ImportConflict conflict;
  final ResolutionAction action;
  final String? newCode;

  ConflictResolution({
    required this.conflict,
    required this.action,
    this.newCode,
  });

  bool get requiresNewCode => action == ResolutionAction.addAsNew;
}

// Standard door inspection errors
class DoorErrorCatalog {
  static List<ErrorCatalog> getStandardErrors() {
    return [
      // Fehler ohne Nummer (automatisch generierte Codes)
      ErrorCatalog(
        code: 'ERR-001',
        category: 'Allgemein',
        description: 'Warum ist Stangengriff und aber kein AP Schloss verbaut?',
        severity: 'medium',
        recommendation: 'Schlosskonzept überprüfen und anpassen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-002',
        category: 'Zarge',
        description: 'Zarge lose im untere Bereich von Türband',
        severity: 'high',
        recommendation: 'Zargenbefestigung überprüfen und nacharbeiten',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-003',
        category: 'Bodenbelag',
        description: 'Dichtungskeile fehlen',
        severity: 'medium',
        recommendation: 'Dichtungskeile nachrüsten',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-004',
        category: 'Glasleiste',
        description: 'Glasleiste fehlt',
        severity: 'medium',
        recommendation: 'Glasleiste nachrüsten',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-005',
        category: 'Handauslösetaster',
        description: 'Handauslösetaster fehlt',
        severity: 'high',
        recommendation: 'Handauslösetaster nachrüsten',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-006',
        category: 'Kennzeichnung',
        description: 'Kennzeichnung des Schließbereiches fehlt',
        severity: 'medium',
        recommendation: 'Kennzeichnung des Schließbereiches anbringen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-007',
        category: 'Befestigung',
        description: 'Befestigung Mehrfachverriegelung',
        severity: 'high',
        recommendation: 'Befestigung überprüfen und nacharbeiten',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-008',
        category: 'Türflügel',
        description: 'Flügel sitzen auf dem Teppich auf',
        severity: 'medium',
        recommendation: 'Türflügel einstellen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-009',
        category: 'RMZ',
        description: 'RMZ ohne Verschmutzungskompensation',
        severity: 'medium',
        recommendation: 'RMZ mit Verschmutzungskompensation austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-010',
        category: 'Taster',
        description: 'Tür schließen Taster falsche Form/Farbe',
        severity: 'low',
        recommendation: 'Taster austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-011',
        category: 'Bandbuchse',
        description: 'Bandbuchse fehlt',
        severity: 'medium',
        recommendation: 'Bandbuchse nachrüsten',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-012',
        category: 'Handauslösetaster',
        description: 'Handauslösetaster ohne Funktion',
        severity: 'high',
        recommendation: 'Handauslösetaster reparieren oder austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-013',
        category: 'RMZ',
        description: 'RMZ ohne Funktion',
        severity: 'high',
        recommendation: 'RMZ reparieren oder austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-014',
        category: 'GSR',
        description: 'GSR mit RMZ ohne Zulassung',
        severity: 'critical',
        recommendation: 'GSR mit zugelassenem RMZ austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-015',
        category: 'RSZ',
        description: 'RSZ verschmutzt',
        severity: 'medium',
        recommendation: 'RSZ reinigen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-016',
        category: 'RSZ',
        description: 'Hekatron RSZ verschmutzt',
        severity: 'medium',
        recommendation: 'Hekatron RSZ reinigen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-017',
        category: 'Bodenschwelle',
        description: 'Bodenschwelle neumontage',
        severity: 'medium',
        recommendation: 'Bodenschwelle neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-018',
        category: 'Exzenterbuchse',
        description: 'Exzenterbuchse ersetzen',
        severity: 'medium',
        recommendation: 'Exzenterbuchse austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-019',
        category: 'Hinweis',
        description: 'Hinweis: Handauslösetaster unzulässig',
        severity: 'low',
        recommendation: 'Handauslösetaster prüfen und ggf. entfernen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-020',
        category: 'Hinweis',
        description: 'Hinweis: Kennzeichnung des Schließbereiches der Feststellanlage fehlt',
        severity: 'low',
        recommendation: 'Kennzeichnung anbringen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-021',
        category: 'Sonstiges',
        description: 'Siehe Text',
        severity: 'medium',
        recommendation: 'Details in Inspektionsprotokoll prüfen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-022',
        category: 'Fluchttürwächter',
        description: 'Fluchttürwächter Schwenk',
        severity: 'medium',
        recommendation: 'Fluchttürwächter einstellen',
        normReference: '',
      ),
      ErrorCatalog(
        code: 'ERR-023',
        category: 'Zulassung',
        description: 'Zulassung verloren',
        severity: 'critical',
        recommendation: 'Zulassung erneuern oder Komponente austauschen',
        normReference: '',
      ),

      // 0.x Fehler
      ErrorCatalog(
        code: '0.1',
        category: 'Bodenbelag',
        description: 'Bodenbelag nicht gemäß Brandschutzanforderungen',
        severity: 'high',
        recommendation: 'Bodenbelag gemäß Brandschutzanforderungen austauschen',
        normReference: 'DIN 4102',
      ),
      ErrorCatalog(
        code: '0.10',
        category: 'Zugang',
        description: 'Kein Zugang / Keine Prüfung',
        severity: 'high',
        recommendation: 'Zugang ermöglichen oder Prüfung nachholen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.11',
        category: 'Fußboden',
        description: 'Fußboden steigt an',
        severity: 'medium',
        recommendation: 'Fußbodenanhebung prüfen und beheben',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.12',
        category: 'Türspalt',
        description: 'Türspalt unten größer als 10 mm',
        severity: 'medium',
        recommendation: 'Türspalt unter 10 mm einstellen',
        normReference: 'DIN 18095',
      ),
      ErrorCatalog(
        code: '0.13',
        category: 'Türspalt',
        description: 'Türspalt unten größer als 20 mm',
        severity: 'high',
        recommendation: 'Türspalt unter 20 mm einstellen',
        normReference: 'DIN 18095',
      ),
      ErrorCatalog(
        code: '0.14',
        category: 'Fluchtweg',
        description: 'Fluchtwegsituation sollte überprüft werden',
        severity: 'medium',
        recommendation: 'Fluchtwegsituation prüfen',
        normReference: 'ASR A1.3',
      ),
      ErrorCatalog(
        code: '0.15',
        category: 'Kennzeichnung',
        description: 'Kein Kennzeichnungsschild an der Tür',
        severity: 'medium',
        recommendation: 'Kennzeichnungsschild anbringen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.16',
        category: 'Feststellung',
        description: 'Unzulässige Feststelllung der Brand- und/oder Rauchschutztür',
        severity: 'critical',
        recommendation: 'Feststellung entfernen oder genehmigen lassen',
        normReference: 'DIN 18095',
      ),
      ErrorCatalog(
        code: '0.17',
        category: 'Sturz',
        description: 'Sturz über 1 Meter. Zusätzliche Deckenrauchschalter erforderlich',
        severity: 'high',
        recommendation: 'Zusätzliche Deckenrauchschalter installieren',
        normReference: 'DIN 14675',
      ),
      ErrorCatalog(
        code: '0.18',
        category: 'Sturzmelder',
        description: 'Sturzmelder ist falsch montiert. RM ist verdeckt bzw. hat weniger als 10 mm Luft nach oben.',
        severity: 'high',
        recommendation: 'Sturzmelder korrekt montieren',
        normReference: 'DIN 14675',
      ),
      ErrorCatalog(
        code: '0.19',
        category: 'Fluchtwegbeschilderung',
        description: 'Fluchtwegbeschilderung höher setzen',
        severity: 'medium',
        recommendation: 'Fluchtwegbeschilderung in korrekter Höhe anbringen',
        normReference: 'ASR A1.3',
      ),
      ErrorCatalog(
        code: '0.2',
        category: 'Feststellanlage',
        description: 'Abnahmeschild der Feststellanlage fehlt',
        severity: 'medium',
        recommendation: 'Abnahmeschild anbringen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.20',
        category: 'Fluchtwegbeschilderung',
        description: 'Fluchtwegbeschilderung/Fluchtwegplan nicht vorhanden bzw. unvollständig',
        severity: 'high',
        recommendation: 'Fluchtwegbeschilderung und -plan vervollständigen',
        normReference: 'ASR A1.3',
      ),
      ErrorCatalog(
        code: '0.22',
        category: 'Drehflügelantrieb',
        description: 'Drehflügelantrieb entspricht nicht den aktuellen Richtlinien',
        severity: 'high',
        recommendation: 'Drehflügelantrieb austauschen',
        normReference: 'EN 16005',
      ),
      ErrorCatalog(
        code: '0.23',
        category: 'Drehflügelantrieb',
        description: 'Drehflügelantrieb ohne Funktion',
        severity: 'critical',
        recommendation: 'Drehflügelantrieb reparieren oder austauschen',
        normReference: 'EN 16005',
      ),
      ErrorCatalog(
        code: '0.24',
        category: 'Verglasung',
        description: 'Verglasung defekt',
        severity: 'medium',
        recommendation: 'Verglasung austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.25',
        category: 'Brandschutzverglasung',
        description: 'Brandschutzverglasung ist defekt',
        severity: 'high',
        recommendation: 'Brandschutzverglasung austauschen',
        normReference: 'DIN 4102',
      ),
      ErrorCatalog(
        code: '0.26',
        category: 'Dokumentation',
        description: 'Erstwartung und Datenaufnahme weiterer Türen zum Nachweis',
        severity: 'low',
        recommendation: 'Weitere Türen dokumentieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.27',
        category: 'Bodenbelag',
        description: 'Teppichboden unter der Bodendichtung der Tür',
        severity: 'medium',
        recommendation: 'Teppichboden entfernen oder Bodendichtung anpassen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.28',
        category: 'Panikfunktion',
        description: 'Keine Prüfung der Panikfunktion möglich',
        severity: 'high',
        recommendation: 'Panikfunktion prüfbar machen',
        normReference: 'DIN 17950',
      ),
      ErrorCatalog(
        code: '0.29',
        category: 'Brandschutztür',
        description: 'Brand- und/oder Rauchschutztür ist defekt',
        severity: 'critical',
        recommendation: 'Brand- und/oder Rauchschutztür instand setzen',
        normReference: 'DIN 18095',
      ),
      ErrorCatalog(
        code: '0.3',
        category: 'Rauchschalter',
        description: 'Die Rauchschalter sind ohne Funktion',
        severity: 'high',
        recommendation: 'Rauchschalter reparieren oder austauschen',
        normReference: 'DIN 14675',
      ),
      ErrorCatalog(
        code: '0.30',
        category: 'Fußboden',
        description: 'Fußboden ist uneben / Behinderung der Bodendichtung',
        severity: 'medium',
        recommendation: 'Fußboden ebenen oder Bodendichtung anpassen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.32',
        category: 'Brand- und Rauchschutzkonzept',
        description: 'Das Brand- und Rauchschutzkonzept sollte überprüft werden.',
        severity: 'medium',
        recommendation: 'Brand- und Rauchschutzkonzept überprüfen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.4',
        category: 'Feststellanlage',
        description: 'Keine Zentrale einer Feststellanlage an der Tür erkennbar',
        severity: 'medium',
        recommendation: 'Zentrale der Feststellanlage erkennbar machen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.5',
        category: 'Kennzeichnung',
        description: 'Falsches Kennzeichnungsschild der Tür',
        severity: 'medium',
        recommendation: 'Korrektes Kennzeichnungsschild anbringen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.6',
        category: 'Bodenbelag',
        description: 'Parkettboden unter der Bodendichtung der Tür',
        severity: 'medium',
        recommendation: 'Parkettboden entfernen oder Bodendichtung anpassen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.7',
        category: 'Bodenbelag',
        description: 'Laminatbelag unter der Bodendichtung der Tür',
        severity: 'medium',
        recommendation: 'Laminatbelag entfernen oder Bodendichtung anpassen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '0.8',
        category: 'Standflügel',
        description: 'Standflügel lässt sich nicht öffnen',
        severity: 'critical',
        recommendation: 'Standflügel öffnungsfähig machen',
        normReference: 'DIN 17950',
      ),
      ErrorCatalog(
        code: '0.9',
        category: 'EMF',
        description: 'EMF ohne Funktion und Strom',
        severity: 'critical',
        recommendation: 'EMF instand setzen und Stromversorgung herstellen',
        normReference: '',
      ),

      // 1.x Fehler - Türflügel/Bänder einstellen
      ErrorCatalog(
        code: '1.1',
        category: 'Türflügel/Bänder',
        description: 'Türflügel/Bänder richten und einstellen (2 Mann)',
        severity: 'high',
        recommendation: 'Türflügel und Bänder richten und einstellen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.10',
        category: 'Bodenhülse',
        description: 'Bodenhülse ersetzen',
        severity: 'medium',
        recommendation: 'Bodenhülse austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.12',
        category: 'Kennzeichnungsschild',
        description: 'Kennzeichnungsschild Neubefestigung',
        severity: 'low',
        recommendation: 'Kennzeichnungsschild neu befestigen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.13',
        category: 'Türanschluss',
        description: 'Unteren Türanschluss fachgerecht herstellen',
        severity: 'medium',
        recommendation: 'Unteren Türanschluss fachgerecht herstellen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.14',
        category: 'Türflügel/Bänder',
        description: 'Türflügel/Bänder richten und einstellen (2 Mann)',
        severity: 'high',
        recommendation: 'Türflügel und Bänder richten und einstellen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.16',
        category: 'Standflügelverriegelung',
        description: 'Standflügelverriegelung austauschen (2 Mann)',
        severity: 'high',
        recommendation: 'Standflügelverriegelung austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.17',
        category: 'Treibriegelschloss',
        description: 'Treibriegelschloss (Vollpanik) austauschen (2 Mann)',
        severity: 'high',
        recommendation: 'Treibriegelschloss austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.18',
        category: 'Türzarge',
        description: 'Türzarge ist lose. Neubefestigen und vermörteln.',
        severity: 'high',
        recommendation: 'Türzarge neubefestigen und vermörteln',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.19',
        category: 'Bodentürstopper',
        description: 'Bodentürstopper 1070 Edelstahl matt Neumontage',
        severity: 'medium',
        recommendation: 'Bodentürstopper neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.2',
        category: 'Standflügelverriegelung',
        description: 'Standflügelverriegelung reparieren (2 Mann)',
        severity: 'high',
        recommendation: 'Standflügelverriegelung reparieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.20',
        category: 'Brandschutzverglasung',
        description: 'Austausch der Brandschutzverglasung (2 Mann)',
        severity: 'high',
        recommendation: 'Brandschutzverglasung austauschen',
        normReference: 'DIN 4102',
      ),
      ErrorCatalog(
        code: '1.21',
        category: 'Glasleiste',
        description: 'Glasleiste gem. bauseitigen Muster',
        severity: 'medium',
        recommendation: 'Glasleiste gemäß bauseitigem Muster austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.22',
        category: 'Kennzeichnungsschild',
        description: '2 Stück Kennzeichnungsschilder "Feuerschutzabschluss - Schließbereich freihalten nach DIN 4066"',
        severity: 'medium',
        recommendation: 'Kennzeichnungsschilder anbringen',
        normReference: 'DIN 4066',
      ),
      ErrorCatalog(
        code: '1.3',
        category: 'Schließblech/Beschlag',
        description: 'Schließblech/ Beschlag reparieren bzw. befestigen',
        severity: 'medium',
        recommendation: 'Schließblech/Beschlag reparieren oder befestigen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.6',
        category: 'Mitnehmerklappe',
        description: 'Mitnehmerklappe für Vollpanik Nachrüsten',
        severity: 'medium',
        recommendation: 'Mitnehmerklappe nachrüsten',
        normReference: '',
      ),

      // 1.7.x - Bodendichtung erneuern (1 Mann)
      ErrorCatalog(
        code: '1.7.1',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-15/30 WS 960 erneuern',
        severity: 'medium',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.10',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 1270 erneuern',
        severity: 'medium',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.11',
        category: 'Bodendichtung',
        description: 'BD Athmer BRB-52 L=1011(Kürzb666mm)',
        severity: 'medium',
        recommendation: 'BD Athmer Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.11',
        category: 'Bodendichtung',
        description: 'Hörmann Bodendichtung 1011 erneuern',
        severity: 'medium',
        recommendation: 'Hörmann Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.13',
        category: 'Bodendichtung',
        description: 'Wirus Bodendichtung 835 erneuern',
        severity: 'medium',
        recommendation: 'Wirus Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.14',
        category: 'Bodendichtung',
        description: 'Wirus Bodendichtung 960 erneuern',
        severity: 'medium',
        recommendation: 'Wirus Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.15',
        category: 'Bodendichtung',
        description: 'Wirus Bodendichtung 1085 erneuern',
        severity: 'medium',
        recommendation: 'Wirus Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.16',
        category: 'Bodendichtung',
        description: 'Wirus Bodendichtung 1210 erneuern',
        severity: 'medium',
        recommendation: 'Wirus Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.17',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 708 (ein) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.18',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 833 (ein) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.19',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 958 (ein) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.2',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-15 WS 1085 erneuern',
        severity: 'medium',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.20',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 1083 (ein) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.21',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 1208 (ein) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.22',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 708 (zwei) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.23',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 833 (zwei) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.24',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 958 (zwei) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.25',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 1083 (zwei) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.26',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung 20/17 1208 (zwei) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.3',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 1470 erneuern',
        severity: 'medium',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.4',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung (unbekanntes Modell) erneuern',
        severity: 'medium',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.5',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 325 erneuern',
        severity: 'medium',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.6',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 405 erneuern',
        severity: 'medium',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.7',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 470 erneuern',
        severity: 'medium',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.8',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 670 erneuern',
        severity: 'medium',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.7.9',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 1070 erneuern',
        severity: 'medium',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),

      // 1.8.x - Bodendichtung erneuern (2 Mann)
      ErrorCatalog(
        code: '1.8.1',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-15/30 WS 1210 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.10',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-24/20 ES 833 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.11',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-24/20 ES 958 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.12',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-24/20 ES 1083 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.13',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-24/20 ES 1208 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.2',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-24/20 WS 1050 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.3',
        category: 'Bodendichtung',
        description: 'Auto Bodendichtung (unbekanntes Modell) erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Auto Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.4',
        category: 'Bodendichtung',
        description: 'BD Athmer BRB-52 L=1011(Kürzb666mm)(2Mann)',
        severity: 'high',
        recommendation: 'BD Athmer Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.5',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-24/20 WS 1350 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.6',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 670 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.7',
        category: 'Bodendichtung',
        description: 'Schüco Bodendichtung 1070 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Schüco Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.8',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-15/30 WS 1085 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.8.9',
        category: 'Bodendichtung',
        description: 'Bodendichtung L-24/20 ES 708 erneuern (2 Mann)',
        severity: 'high',
        recommendation: 'Bodendichtung erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '1.9.1',
        category: 'Schließfolgeregelung',
        description: 'Schließfolgeregelung dormakaba Austausch',
        severity: 'medium',
        recommendation: 'Schließfolgeregelung austauschen',
        normReference: '',
      ),

      // 10.x - Anschlagdichtung
      ErrorCatalog(
        code: '10.1',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Stahlblechtüren Z7511',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.1.1',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Stahlblechtüren (Hörmann) Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.1x',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Stahlblechtüren Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.2.1',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für RR-Türen (unbekannter Typ) Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.2.2',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für SCHÜCO RR-Türen Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.3.1',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Holzüren (Novoferm) Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.3.2',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Holzüren (Schörghuber) Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.3.3',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Holzüren (Westag & Getalit) Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.3.4',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Holzüren (Herholz 4) Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.3.x',
        category: 'Anschlagdichtung',
        description: 'Anschlagdichtung für FH-Holztüren Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Anschlagdichtung austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.4.x',
        category: 'Brandschutzstreifen',
        description: 'Brandschutzstreifen je Flügel Austausch/Ergänzung',
        severity: 'medium',
        recommendation: 'Brandschutzstreifen austauschen/ergänzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '10.5x',
        category: 'Wandanschluss',
        description: 'Wandanschluss wiederherstellen',
        severity: 'medium',
        recommendation: 'Wandanschluss wiederherstellen',
        normReference: '',
      ),

      // 11.x - ED 250 Drehflügelantriebe
      ErrorCatalog(
        code: '11.1',
        category: 'ED 250',
        description: 'ED 250 für 1 flügelige Türen bis 400 kg oder 1.100 mm Breite, Brandschutz Montageart Gleitschiene Bandgegenseite',
        severity: 'high',
        recommendation: 'ED 250 montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.10',
        category: 'ED 250',
        description: 'Fehlersuche am Dorma ED 250 zum Material- und Stundenweis',
        severity: 'medium',
        recommendation: 'Fehlersuche durchführen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.11',
        category: 'ED 250',
        description: 'ED 250 Normalgestänge ersetzen',
        severity: 'medium',
        recommendation: 'Normalgestänge ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.12',
        category: 'ED 250',
        description: 'Austausch Taster"Tür verriegeln" und Statusanzeige rot/grün',
        severity: 'medium',
        recommendation: 'Taster und Statusanzeige austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.13',
        category: 'ED 250',
        description: 'Reparatur IRS-4 Sensorleiste (Austausch einer Optik)',
        severity: 'medium',
        recommendation: 'Sensorleiste reparieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.2',
        category: 'ED 250',
        description: 'ED 250 für 1 flügelige Türen bis 400 kg oder 1.600 mm Breite, Brandschutz Montageart Bandgegenseite',
        severity: 'high',
        recommendation: 'ED 250 montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.3',
        category: 'ED 250',
        description: 'ED 250 1 flügelige Türen bis 400 kg oder 1.400 mm Breite, Brandschutz Montageart Bandseite',
        severity: 'high',
        recommendation: 'ED 250 montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.4',
        category: 'ED 250',
        description: 'ED 250 für1 flügelige Türen bis 400 kg oder 1.600 mm Breite, Low Energy Montageart Bandseite',
        severity: 'high',
        recommendation: 'ED 250 montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.5',
        category: 'ED 250',
        description: 'Fingerschutzrollo Nachrüstung',
        severity: 'medium',
        recommendation: 'Fingerschutzrollo nachrüsten',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.6',
        category: 'ED 250',
        description: 'Sensorleisten 1100 Nachrüstung',
        severity: 'medium',
        recommendation: 'Sensorleisten nachrüsten',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.7',
        category: 'ED 250',
        description: 'ED 250 für1 flügelige Türen bis 400 kg oder 1.600 mm Breite, Low Energy Montageart Bandgegenseite',
        severity: 'high',
        recommendation: 'ED 250 montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.8',
        category: 'ED 250',
        description: 'ED 250 für 1 flügelige Türen bis 400 kg oder 1.600 mm Breite, Full Energy Montageart Bandseite',
        severity: 'high',
        recommendation: 'ED 250 montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '11.9',
        category: 'ED 250',
        description: 'ED 250 für 1 flügelige Türen bis 400 kg oder 1.600 mm Breite, Full Energy Montageart Bandgegenseite',
        severity: 'high',
        recommendation: 'ED 250 montieren',
        normReference: '',
      ),

      // 11.14 - 11.39 (zusätzliche ED 250 Varianten)
      ErrorCatalog(
        code: '11.14',
        category: 'ED 250',
        description: 'Flatscan Nachrüstung an Drehflügelantrieb (1 Paar)',
        severity: 'medium',
        recommendation: 'Flatscan nachrüsten',
        normReference: '',
      ),

      // 12.x - GEZE Komponenten
      ErrorCatalog(
        code: '12.2',
        category: 'GEZE',
        description: 'GEZE Nottaster Nachrüstung',
        severity: 'medium',
        recommendation: 'GEZE Nottaster nachrüsten',
        normReference: '',
      ),
      ErrorCatalog(
        code: '12.3',
        category: 'GEZE',
        description: 'GEZE Schiebetür Steuerung Austausch',
        severity: 'medium',
        recommendation: 'GEZE Schiebetür Steuerung austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '12.4',
        category: 'GEZE',
        description: 'GEZE Displayprogrammschalter Austausch',
        severity: 'medium',
        recommendation: 'GEZE Displayprogrammschalter austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '12.5',
        category: 'GEZE',
        description: 'Dorma ES 200 Notstromakkutausch (2 Stück)',
        severity: 'medium',
        recommendation: 'Notstromakkus austauschen',
        normReference: '',
      ),

      // 13.x - Abnahme
      ErrorCatalog(
        code: '13.1',
        category: 'Abnahme',
        description: 'Abnahme mit Prüfbuch und Zulassungsetikett',
        severity: 'low',
        recommendation: 'Abnahme durchführen',
        normReference: '',
      ),

      // 14.x - RWA
      ErrorCatalog(
        code: '14.1',
        category: 'RWA',
        description: 'RWA Notstromakku Austausch',
        severity: 'medium',
        recommendation: 'RWA Notstromakku austauschen',
        normReference: '',
      ),

      // 16.x - Sonstiges
      ErrorCatalog(
        code: '16.3',
        category: 'Gerüst',
        description: 'Gerüststellung für De- und Montagearbeiten',
        severity: 'low',
        recommendation: 'Gerüst stellen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '16.4',
        category: 'Dokumentation',
        description: 'Erstwartung und Datenaufnahme weiterer Türen zum Stundennachweis',
        severity: 'low',
        recommendation: 'Weitere Türen dokumentieren',
        normReference: '',
      ),

      // 2.x - Türband
      ErrorCatalog(
        code: '2.1.x',
        category: 'Türband',
        description: 'Türband Reparatur (1 Mann)',
        severity: 'medium',
        recommendation: 'Türband reparieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '2.2.x',
        category: 'Türband',
        description: 'Türband für RR Tür Neu (2 Mann)',
        severity: 'high',
        recommendation: 'Türband neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '2.3.x',
        category: 'Türband',
        description: 'Federband Stahlblechtür Austausch',
        severity: 'medium',
        recommendation: 'Federband austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '2.4',
        category: 'Türband',
        description: 'Türband Neubefestigung (2 Mann)',
        severity: 'high',
        recommendation: 'Türband neubefestigen',
        normReference: '',
      ),

      // 3.x - Schlösser
      ErrorCatalog(
        code: '3.1.1',
        category: 'Schloss',
        description: 'FH Fallen-Riegelschloss ersetzen',
        severity: 'medium',
        recommendation: 'Fallen-Riegelschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.1.2',
        category: 'Schloss',
        description: 'FH Fallen-Riegelschloss R/L ersetzen',
        severity: 'medium',
        recommendation: 'Fallen-Riegelschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.1.x',
        category: 'Schloss',
        description: 'FH Fallen-Riegelschloss ersetzen',
        severity: 'medium',
        recommendation: 'Fallen-Riegelschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.1',
        category: 'Schloss',
        description: 'FH-Anti-Panikschloss-B 65/72/9/20/235/FR/R',
        severity: 'medium',
        recommendation: 'Anti-Panikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.2',
        category: 'Schloss',
        description: 'RR Schloss Funktion B Schüco ersetzen (Sonderbeschaffung)',
        severity: 'medium',
        recommendation: 'Schloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.3',
        category: 'Schloss',
        description: 'FH-Antipanikschloss 65/72/24/9 ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.3',
        category: 'Schloss',
        description: 'FH-Antipanikschloss B/65/72/24/9/DL ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.3 x',
        category: 'Schloss',
        description: 'FH-Anti-Panikschloss-B 55/72/9/20/235/FR/L',
        severity: 'medium',
        recommendation: 'Anti-Panikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.4',
        category: 'Schloss',
        description: 'FH-Antipanikschloss B/65/72/24/9/DLE ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.5',
        category: 'Schloss',
        description: 'FH-Antipanikschloss B/65/72/24/9/DR ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.6',
        category: 'Schloss',
        description: 'FH-Antipanikschloss B/65/72/24/9/DRE ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.2.x',
        category: 'Schloss',
        description: 'FH Antipanikschloss "B" ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.3.2',
        category: 'Schloss',
        description: 'RR Schloss Funktion E Schüco ersetzen (Sonderbeschaffung)',
        severity: 'medium',
        recommendation: 'Schloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.3.4',
        category: 'Schloss',
        description: 'FH Antipanikschloss "E" L/R ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.3.5',
        category: 'Schloss',
        description: 'Schloss mit Schrägstulp mit Panikfunktion E Neumontage',
        severity: 'medium',
        recommendation: 'Schloss neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.3.6',
        category: 'Schloss',
        description: 'FH Antipanikschloss "E" Neumontage einschl.Wechselganitur',
        severity: 'medium',
        recommendation: 'Antipanikschloss neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.3.x',
        category: 'Schloss',
        description: 'FH Antipanikschloss "E" ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.4.1',
        category: 'Schloss',
        description: 'FH Antipanikschloss "D" ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.4.2',
        category: 'Schloss',
        description: 'FH Antipanikschloss R/L "D" ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.4.x',
        category: 'Schloss',
        description: 'FH Antipanikschloss "D" ersetzen',
        severity: 'medium',
        recommendation: 'Antipanikschloss ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '3.5',
        category: 'Schloss',
        description: 'E-Öffner Schüco ersetzen',
        severity: 'medium',
        recommendation: 'E-Öffner ersetzen',
        normReference: '',
      ),

      // 4.x - Türbeschläge
      ErrorCatalog(
        code: '4.1',
        category: 'Türbeschlag',
        description: 'Türbeschlag neu befestigen',
        severity: 'medium',
        recommendation: 'Türbeschlag neu befestigen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.10',
        category: 'Türbeschlag',
        description: 'Drücker mit Einnietmuttern M5 neu befestigen',
        severity: 'medium',
        recommendation: 'Drücker neu befestigen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.11',
        category: 'Türbeschlag',
        description: 'PZ Rosetten Edelstahl oval',
        severity: 'low',
        recommendation: 'PZ Rosetten austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.12',
        category: 'Türbeschlag',
        description: 'Drückergarnitur Edelstahl oval RR 9 im Austausch',
        severity: 'medium',
        recommendation: 'Drückergarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.13',
        category: 'Türbeschlag',
        description: 'Drückergarnitur Aluminium oval RR 9 im Austausch',
        severity: 'medium',
        recommendation: 'Drückergarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.14',
        category: 'Türbeschlag',
        description: 'Wechselgarnitur Edelstahl oval RR 9 im Austausch',
        severity: 'medium',
        recommendation: 'Wechselgarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.15',
        category: 'Türbeschlag',
        description: 'Wechselgarnitur Aluminium oval RR 9 im Austausch',
        severity: 'medium',
        recommendation: 'Wechselgarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.17',
        category: 'Türbeschlag',
        description: 'AP Pushbar reparieren',
        severity: 'medium',
        recommendation: 'AP Pushbar reparieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.18 x',
        category: 'Türbeschlag',
        description: 'FH Wechsel-Kurzschild-Garnitur KS Schwarz',
        severity: 'medium',
        recommendation: 'Wechsel-Kurzschild-Garnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.19',
        category: 'Türbeschlag',
        description: 'Antipanik Drückergarnitur Edelstahl rund VB 9 im Austausch',
        severity: 'medium',
        recommendation: 'Drückergarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.2',
        category: 'Türbeschlag',
        description: 'FH Drücker-Kurzschild-Garnitur KS schwarz ersetzen',
        severity: 'medium',
        recommendation: 'Drücker-Kurzschild-Garnitur ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.20',
        category: 'Türbeschlag',
        description: 'Drückergarnitur Edelstahl rund VB 9 im Austausch',
        severity: 'medium',
        recommendation: 'Drückergarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.21',
        category: 'Türbeschlag',
        description: 'Wechselgarnitur Edelstahl rund VB 9 im Austausch',
        severity: 'medium',
        recommendation: 'Wechselgarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.22',
        category: 'Türbeschlag',
        description: 'Antipanik Drückergarnitur Aluminium rund VB 9 im Austausch',
        severity: 'medium',
        recommendation: 'Drückergarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.23',
        category: 'Türbeschlag',
        description: 'Drückergarnitur Aluminium rund VB 9 im Austausch',
        severity: 'medium',
        recommendation: 'Drückergarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.24',
        category: 'Türbeschlag',
        description: 'Wechselgarnitur Aluminium rund VB 9 im Austausch',
        severity: 'medium',
        recommendation: 'Wechselgarnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.3',
        category: 'Türbeschlag',
        description: 'FH Drücker-Kurzschild-Garnitur Alu ersetzen',
        severity: 'medium',
        recommendation: 'Drücker-Kurzschild-Garnitur ersetzen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.4.1',
        category: 'Türbeschlag',
        description: 'Blindzylinder variabel 52-90 BS/RS',
        severity: 'medium',
        recommendation: 'Blindzylinder austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.4.2',
        category: 'Türbeschlag',
        description: 'Blindzylinder variabel 84-144 BS/RS',
        severity: 'medium',
        recommendation: 'Blindzylinder austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.5 x',
        category: 'Türbeschlag',
        description: 'FH Wechsel-Kurzschild-Garnitur Edelstahl',
        severity: 'medium',
        recommendation: 'Wechsel-Kurzschild-Garnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.6',
        category: 'Türbeschlag',
        description: 'FH Wechsel-Kurzschild-Garnitur Alu',
        severity: 'medium',
        recommendation: 'Wechsel-Kurzschild-Garnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.7',
        category: 'Türbeschlag',
        description: 'BS Drücker-Langschild-Garnitur Edelstahl',
        severity: 'medium',
        recommendation: 'Drücker-Langschild-Garnitur austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.8',
        category: 'Türbeschlag',
        description: 'PZ Rosetten Alu',
        severity: 'low',
        recommendation: 'PZ Rosetten austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.9 x',
        category: 'Türbeschlag',
        description: 'BKS Panik Griffstange erneuern',
        severity: 'medium',
        recommendation: 'Panik Griffstange erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '4.9 x',
        category: 'Türbeschlag',
        description: 'Panik Griffstange',
        severity: 'medium',
        recommendation: 'Panik Griffstange erneuern',
        normReference: '',
      ),

      // 5.x - Obentürschließer
      ErrorCatalog(
        code: '5.1',
        category: 'Obentürschließer',
        description: 'Obentürschließer neu befestigen',
        severity: 'medium',
        recommendation: 'Obentürschließer neu befestigen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.10',
        category: 'Obentürschließer',
        description: 'TS 83 B/N Austausch',
        severity: 'medium',
        recommendation: 'TS 83 austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.11',
        category: 'Obentürschließer',
        description: 'TS 83 B/N Neumontage',
        severity: 'medium',
        recommendation: 'TS 83 neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.12',
        category: 'Obentürschließer',
        description: 'TS 89F B/N Austausch (Sonderbeschaffung)',
        severity: 'medium',
        recommendation: 'TS 89F austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.13',
        category: 'Obentürschließer',
        description: 'TS GEZE 5000 mit Gleitschiene ISM Neumontage',
        severity: 'medium',
        recommendation: 'TS GEZE 5000 neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.14',
        category: 'Obentürschließer',
        description: 'TS GEZE 4000 mit Gestänge Austausch',
        severity: 'medium',
        recommendation: 'TS GEZE 4000 austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.15',
        category: 'Obentürschließer',
        description: 'TS GEZE 5000 mit Gleitschiene Austausch',
        severity: 'medium',
        recommendation: 'TS GEZE 5000 austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.16',
        category: 'Obentürschließer',
        description: 'DORMA Gleitschiene G-N Erneuerung',
        severity: 'medium',
        recommendation: 'DORMA Gleitschiene erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.17',
        category: 'Obentürschließer',
        description: 'DORMA Hebel 375 mm für G-N, G-EMF, G-EMR, GSR Erneuerung',
        severity: 'medium',
        recommendation: 'DORMA Hebel erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.18',
        category: 'Obentürschließer',
        description: 'DORMA G-N Gleitstück inkl. Schraube Erneuerung',
        severity: 'medium',
        recommendation: 'DORMA Gleitstück erneuern',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.19',
        category: 'Obentürschließer',
        description: 'TS 93 mit Gleitschiene Austausch ( 5-7)',
        severity: 'medium',
        recommendation: 'TS 93 austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.3',
        category: 'Obentürschließer',
        description: 'TS GEZE 4000 mit Gestänge Neumontage',
        severity: 'medium',
        recommendation: 'TS GEZE 4000 neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.4',
        category: 'Obentürschließer',
        description: 'TS GEZE 5000 mit Gleitschiene Neumontage',
        severity: 'medium',
        recommendation: 'TS GEZE 5000 neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.5',
        category: 'Obentürschließer',
        description: 'TS 93 mit Gleitschiene Neumontage',
        severity: 'medium',
        recommendation: 'TS 93 neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.6',
        category: 'Obentürschließer',
        description: 'TS 73 B/N Austausch',
        severity: 'medium',
        recommendation: 'TS 73 austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.7',
        category: 'Obentürschließer',
        description: 'TS 73 B/N Neumontage',
        severity: 'medium',
        recommendation: 'TS 73 neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.8',
        category: 'Obentürschließer',
        description: 'ECO TS 61 B-N 2-5 Silberfarbig Austausch',
        severity: 'medium',
        recommendation: 'ECO TS 61 austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '5.9',
        category: 'Obentürschließer',
        description: 'ECO TS 61 B-N 2-5 Silberfarbig Neumontage',
        severity: 'medium',
        recommendation: 'ECO TS 61 neu montieren',
        normReference: '',
      ),

      // 6.x - Feststellanlagen
      ErrorCatalog(
        code: '6.1',
        category: 'Feststellanlage',
        description: 'Feststellanlage G-EMR 80-140°, 1-flg. Austausch',
        severity: 'medium',
        recommendation: 'Feststellanlage austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.10',
        category: 'Feststellanlage',
        description: 'GSR-EMR(ohne EMF) Austausch',
        severity: 'medium',
        recommendation: 'GSR-EMR austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.11',
        category: 'Feststellanlage',
        description: 'GEZE E-Feststelleinheit für R-ISM',
        severity: 'medium',
        recommendation: 'E-Feststelleinheit austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.12x',
        category: 'Feststellanlage',
        description: 'DORMA E-Feststelleinheit für Gleitschiene',
        severity: 'medium',
        recommendation: 'E-Feststelleinheit austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.13',
        category: 'Feststellanlage',
        description: 'Feststellanlage TS 73 EMF, Kopfm, mit Gestänge, BGS, RMZ, Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.14',
        category: 'Feststellanlage',
        description: 'Feststellanlage TS 93 EMF, mit Gleitschiene, BS, RMZ, Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.15',
        category: 'Feststellanlage',
        description: 'Freilauftürschließer TS 99 FLR-K, mit Gleitschiene, NM-BS, RMZ, Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Freilauftürschließer neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.16',
        category: 'Feststellanlage',
        description: 'Freilauftürschließer TS 99 FLR, mit Gleitschiene, KM-BS, RMZ, Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Freilauftürschließer neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.17',
        category: 'Feststellanlage',
        description: 'Feststellanlage RMZ im Contur Design , Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.18',
        category: 'Feststellanlage',
        description: 'Feststellanlage G-Ubivis 80-140°, 1-flg. Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.19',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMR 1, 2 flgl., Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.2',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMR 2, 2 flgl. , Austausch',
        severity: 'medium',
        recommendation: 'Feststellanlage austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.20',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMR 1 G, 2 flgl., Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.21',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMF 1, 2 flgl., Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.22',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMF 1 G, 2 flgl., Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.23',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMF 2, 2 flgl., Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.24',
        category: 'Feststellanlage',
        description: 'Batterietausch Feststellanlage G-Ubivis',
        severity: 'medium',
        recommendation: 'Batterien austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.25',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMR mit 2 HM, 2flg., Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.4',
        category: 'Feststellanlage',
        description: 'Feststellanlage GSR-EMR 2, 2 flgl. , Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.6',
        category: 'Feststellanlage',
        description: 'Feststellanlage G-EMR 80-120°, 1-flg. Austausch',
        severity: 'medium',
        recommendation: 'Feststellanlage austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.7',
        category: 'Feststellanlage',
        description: 'Feststellanlage G-EMR 80-140°, 1-flg. Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.8',
        category: 'Feststellanlage',
        description: 'Feststellanlage G-EMR 80-120°, 1-flg. Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '6.9',
        category: 'Feststellanlage',
        description: 'Feststellanlage G-EMR 80-120°, BG, 1-flg. Neumontage/Umbau',
        severity: 'high',
        recommendation: 'Feststellanlage neu montieren/umbauen',
        normReference: '',
      ),

      // 7.x - Rauchmelder
      ErrorCatalog(
        code: '7. 1',
        category: 'Rauchmeldezentrale',
        description: '1 Rauchmeldezentrale Contur silber im Austausch',
        severity: 'medium',
        recommendation: 'Rauchmeldezentrale austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.1',
        category: 'Rauchmeldezentrale',
        description: 'Rauchmeldezentrale Contur silber im Austausch',
        severity: 'medium',
        recommendation: 'Rauchmeldezentrale austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.10',
        category: 'Handauslösetaster',
        description: 'Korrektur der Montagehöhe des Handauslösetaster',
        severity: 'medium',
        recommendation: 'Montagehöhe korrigieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.11',
        category: 'Deckenrauchmelder',
        description: 'Deckenrauchmelder ORS 142 Stück Neumontage',
        severity: 'medium',
        recommendation: 'Deckenrauchmelder neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.12',
        category: 'Netzteilplatine',
        description: 'Netzteilplatine für RMZ / G-EMR / GSR-EMR / TS 99 FLR-K im Austausch',
        severity: 'medium',
        recommendation: 'Netzteilplatine austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.13',
        category: 'Handauslösetaster',
        description: 'Montage eines Handauslösetaster',
        severity: 'medium',
        recommendation: 'Handauslösetaster montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.2',
        category: 'Sturz-Rauchmelder',
        description: 'Sturz-Rauchmelder RM-ED Contur silber im Austausch',
        severity: 'medium',
        recommendation: 'Sturz-Rauchmelder austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.3',
        category: 'Deckenrauchmelder',
        description: 'Deckenrauchmelder ORS 142 im Austausch',
        severity: 'medium',
        recommendation: 'Deckenrauchmelder austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.4',
        category: 'Deckenrauchmelder',
        description: 'Deckenrauchmelder ORS 142 Paar im Austausch',
        severity: 'medium',
        recommendation: 'Deckenrauchmelder austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.5',
        category: 'Rauchschaltzentrale',
        description: 'Rauchschaltzentrale RSZ 6 im Austausch',
        severity: 'medium',
        recommendation: 'Rauchschaltzentrale austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.6',
        category: 'Raucherkennungsteil',
        description: 'Raucherkennungsteil für RSZ 6 im Austausch',
        severity: 'medium',
        recommendation: 'Raucherkennungsteil austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.7',
        category: 'Stromversorgungsteil',
        description: 'Stromversorgungsteil für RSZ 6 im Austausch',
        severity: 'medium',
        recommendation: 'Stromversorgungsteil austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.8',
        category: 'Rauchschalterplatine',
        description: 'Rauchschalterplatine für G-EMR im Austausch',
        severity: 'medium',
        recommendation: 'Rauchschalterplatine austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '7.9',
        category: 'Deckenrauchmelder',
        description: 'Deckenrauchmelder ORS 142 Paar Neumontage',
        severity: 'medium',
        recommendation: 'Deckenrauchmelder neu montieren',
        normReference: '',
      ),

      // 8.x - Sonstiges
      ErrorCatalog(
        code: '8.1',
        category: 'EH-Türwächter',
        description: 'EH-Türwächter Neumontage',
        severity: 'medium',
        recommendation: 'EH-Türwächter neu montieren',
        normReference: '',
      ),

      // 9.x - Fenster
      ErrorCatalog(
        code: '9.1',
        category: 'Öffnungssperre',
        description: 'Öffnungssperre für Drehfenster Neumontage',
        severity: 'medium',
        recommendation: 'Öffnungssperre neu montieren',
        normReference: '',
      ),
      ErrorCatalog(
        code: '9.2',
        category: 'Drehlager',
        description: 'Drehlager unten SCHÜCO Austausch',
        severity: 'medium',
        recommendation: 'Drehlager austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '9.3x',
        category: 'Drehkippschere',
        description: 'Drehkippschere SCHÜCO Austausch',
        severity: 'medium',
        recommendation: 'Drehkippschere austauschen',
        normReference: '',
      ),
      ErrorCatalog(
        code: '9.4x',
        category: 'Fenstergriff',
        description: 'Fenstergriff abschließbar F1 SCHÜCO Austausch',
        severity: 'medium',
        recommendation: 'Fenstergriff austauschen',
        normReference: '',
      ),
    ];
  }

  static List<String> getCategories() {
    return [
      'Allgemein',
      'Zarge',
      'Bodenbelag',
      'Glasleiste',
      'Handauslösetaster',
      'Kennzeichnung',
      'Befestigung',
      'Türflügel',
      'RMZ',
      'Taster',
      'Bandbuchse',
      'GSR',
      'RSZ',
      'Bodenschwelle',
      'Exzenterbuchse',
      'Hinweis',
      'Sonstiges',
      'Fluchttürwächter',
      'Zulassung',
      'Zugang',
      'Fußboden',
      'Türspalt',
      'Fluchtweg',
      'Feststellung',
      'Sturz',
      'Sturzmelder',
      'Fluchtwegbeschilderung',
      'Drehflügelantrieb',
      'Verglasung',
      'Brandschutzverglasung',
      'Dokumentation',
      'Panikfunktion',
      'Brand- und Rauchschutzkonzept',
      'Standflügel',
      'EMF',
      'Türflügel/Bänder',
      'Bodenhülse',
      'Türanschluss',
      'Standflügelverriegelung',
      'Treibriegelschloss',
      'Bodentürstopper',
      'Kennzeichnungsschild',
      'Schließblech/Beschlag',
      'Mitnehmerklappe',
      'Bodendichtung',
      'Schließfolgeregelung',
      'Anschlagdichtung',
      'Brandschutzstreifen',
      'Wandanschluss',
      'ED 250',
      'Fingerschutzrollo',
      'Sensorleisten',
      'GEZE',
      'Abnahme',
      'RWA',
      'Gerüst',
      'Türband',
      'Federband',
      'Schloss',
      'Anti-Panikschloss',
      'E-Öffner',
      'Türbeschlag',
      'Drücker',
      'Blindzylinder',
      'PZ Rosetten',
      'Panik Griffstange',
      'Obentürschließer',
      'DORMA',
      'TS',
      'ECO TS',
      'Feststellanlage',
      'G-EMR',
      'GSR-EMR',
      'G-Ubivis',
      'Rauchmeldezentrale',
      'Deckenrauchmelder',
      'Netzteilplatine',
      'Sturz-Rauchmelder',
      'Rauchschaltzentrale',
      'Raucherkennungsteil',
      'Stromversorgungsteil',
      'Rauchschalterplatine',
      'EH-Türwächter',
      'Öffnungssperre',
      'Drehlager',
      'Drehkippschere',
      'Fenstergriff',
    ];
  }

  static List<String> getSeverities() {
    return ['low', 'medium', 'high', 'critical'];
  }
}
